POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "My Sweet Lord",
    "author": "George Harrison",
    "url": "https://www.youtube.com/watch?v=XWTvkcHlOPQ&ab_channel=GeorgeHarrison-Topic"
}